version: "3.3"
services:
    student-service-db:
        container_name: student-service-db
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=student_db_pass
            - POSTGRES_USER=akin
            - POSTGRES_DB=student_db
        restart: always
        expose:
            - "5432"
        volumes:
            - ./DB/student-db.sql:/docker-entrypoint-initdb.d/student-db.sql
    api-service:
        container_name: api-service
        environment:
            - NODE_ENV=development
            - PORT=3069
            - STUDENT_DATABASE_DEV_URL=postgres://akin:student_db_pass@student-service-db:5432/student_db
        restart: always
        build: ./server
        links:
            - student-service-db
        depends_on:
            - student-service-db
        ports:
            - "3069:3069"
    client-service:
        container_name: client-service
        environment:
            - REACT_APP_API_BASE_URL=http://localhost:3069
        restart: always
        build: ./client
        links:
            - api-service
        depends_on:
            - api-service
        expose:
            - "3000"
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - client-service
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
