export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const IS_LOADING = 'IS_LOADING';
export const IS_ERROR = 'IS_ERROR';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const FETCH_EDIT_STUDENT_SUCCESS = 'FETCH_EDIT_STUDENT_SUCCESS';