export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const IS_LOADING = 'IS_LOADING';
export const IS_ERROR = 'IS_ERROR';